### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Lextuga007**
I've removed the requirement to install {nottshcMethods} which you might still want - I just didn't understand where this is required.

### CODE REVIEW

**Comment by ChrisBeeley** [comment]
It's here, isn't it?! You told me to install it 😆 
 
image

**Review by ChrisBeeley — CHANGES_REQUESTED** [review]
See my comment about nottshcMethods

**Comment by Lextuga007** [comment]
Oops I did - I wasn't thinking. I've added it back with a note about the template.  You might want to squash or rebase the pull request 😄

**Review by ChrisBeeley — APPROVED** [review]

**Comment by ChrisBeeley** [comment]
Squash/ rebase? What am I? A git ninja? 😉😆

**Pull request merged**
